package middleware

import (
	"fmt"
	"strings"

	"github.com/gofiber/fiber/v2"
	"github.com/golang-jwt/jwt/v5"
	"github.com/ksm/go-invoice/internal/config"
)

// UserClaims represents the authenticated user information
type UserClaims struct {
	UserID uint   `json:"user_id"`
	Name   string `json:"name"`
	Email  string `json:"email"`
	Role   string `json:"role"`
}

// AuthMiddleware validates the JWT token generated by this system
func AuthMiddleware(cfg *config.Config) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var tokenString string

		// First try Authorization header
		authHeader := c.Get("Authorization")
		if authHeader != "" {
			tokenString = strings.TrimPrefix(authHeader, "Bearer ")
			if tokenString == authHeader {
				return c.Status(fiber.StatusUnauthorized).JSON(fiber.Map{
					"success": false,
					"message": "Bearer token required",
				})
			}
		}

		// Fallback to query parameter "token" (used for PDF downloads)
		if tokenString == "" {
			tokenString = c.Query("token")
		}

		if tokenString == "" {
			return c.Status(fiber.StatusUnauthorized).JSON(fiber.Map{
				"success": false,
				"message": "Authorization header or token query required",
			})
		}

		if cfg.JWTSecret == "" {
			return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{
				"success": false,
				"message": "JWT_SECRET is not configured on server",
			})
		}

		claims, err := decodeJWT(tokenString, cfg.JWTSecret)
		if err != nil {
			return c.Status(fiber.StatusUnauthorized).JSON(fiber.Map{
				"success": false,
				"message": "Invalid or expired token",
			})
		}

		// Store user info in context
		c.Locals("user", claims)
		c.Locals("user_id", claims.UserID)
		c.Locals("user_name", claims.Name)
		c.Locals("user_role", claims.Role)

		return c.Next()
	}
}

// decodeJWT decodes the JWT token using our own secret
func decodeJWT(tokenString, secret string) (*UserClaims, error) {
	token, err := jwt.Parse(tokenString, func(token *jwt.Token) (interface{}, error) {
		if _, ok := token.Method.(*jwt.SigningMethodHMAC); !ok {
			return nil, fmt.Errorf("unexpected signing method: %v", token.Header["alg"])
		}
		return []byte(secret), nil
	})

	if err != nil || !token.Valid {
		return nil, fmt.Errorf("invalid token: %w", err)
	}

	mapClaims, ok := token.Claims.(jwt.MapClaims)
	if !ok {
		return nil, fmt.Errorf("invalid claims format")
	}

	claims := &UserClaims{}
	if id, ok := mapClaims["user_id"].(float64); ok {
		claims.UserID = uint(id)
	}
	if name, ok := mapClaims["name"].(string); ok {
		claims.Name = name
	}
	if email, ok := mapClaims["email"].(string); ok {
		claims.Email = email
	}
	if role, ok := mapClaims["role"].(string); ok {
		claims.Role = role
	}

	return claims, nil
}

// RoleMiddleware restricts access to specific roles
func RoleMiddleware(allowedRoles ...string) fiber.Handler {
	return func(c *fiber.Ctx) error {
		role, _ := c.Locals("user_role").(string)
		for _, allowed := range allowedRoles {
			if role == allowed {
				return c.Next()
			}
		}
		return c.Status(fiber.StatusForbidden).JSON(fiber.Map{
			"success": false,
			"message": "Insufficient permissions",
		})
	}
}
